language: ruby
cache: bundler
rvm:
- 2.1
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - gh-pages
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: gcs
  access_key_id: GOOGZOZD2KM62E4KE7P4
  secret_access_key:
    secure:
  bucket: www.brooklinebooksmith.com
  acl: public-read
  detect_encoding: true # <== default is false
  cache_control: "no-cache"
  local-dir: _site
  skip_cleanup: true
  on:
    repo: sonnetmedia/brooklinebooksmith.com
    branch: gh-pages
