url: http://staging-bbs.sonnetmedia.com
sitename: brookline booksmith
description: A base Jekyll theme
timezone: Etc/Zulu
address_for_nav: "279 Harvard St. (at Beacon St.) &bull; 617-566-6660"
include:
  - _pages
exclude:
  - readme.md
  - todo.md
  - license.md
  - Gemfile
  - Gemfile.lock
  - bower.json
  - CNAME
  - node_modules
  - sass
  - gulpfile.js
  - package.json
  - javascript
permalink: pretty
future: true
production: false
bust_css_cache: true
google_analytics_id: UA-xxxx
typekit_id: saz8dbz
include_nav-top: true
include_nav-side-left: true
include_nav-side-right: false
venues:
  - '-'
  - In-store
  - "Coolidge Corner Theater"
  - Other
fancy_fonts:
  - ''
  - 'Fredericka+the+Great'
  - 'Cabin-sketch'
directory_assets_img: /static/images/
twitter_id: budparr
collections:
  articles:
    output: true
    permalink: '/:collection/:path/'
  landing_pages:
    output: true
    permalink: '/:path/'
  events:
    output: true
    permalink: '/:collection/:path/'
    future: true
  programs:
    output: true
    permalink: '/:collection/:path/'
  books:
    output: false
  book_categories:
    output: true
    permalink: '/genre/:path/'
defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: page
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: ''
      type: events
    values:
      layout: page
  - scope:
      path: ''
      type: landing_pages
    values:
      layout: landing_page
  - scope:
      path: ''
      type: programs
    values:
      layout: page
