# jekyll-seo-tag
title: brookline booksmith
description: "Brookline Booksmith is an stablished independent bookshop offering new & used titles, plus gifts, over 2 floors."
url: https://www.brooklinebooksmith.com
author: []
twitter:
  username: booksmithtweets
facebook:
  app_id:
  publisher:
  admins:
logo: https://www.brooklinebooksmith.com/uploads/banner-home-page_wr.jpg
addthis_id: 561d1f58a8154d03

address_for_nav: "279 Harvard St. (at Beacon St.) <br /> 617-566-6660"
address: "279 Harvard St, Brookline, Massachusetts 02446-2908"

newsletter_copy: "Join our mailing list to get b-mail, our weekly newsletter"
venues:
  - '-'
  - In-store
  - "Coolidge Corner Theater"
  - Other
categories:
  - ''
  - kidsmith
  - this-week-in-books
  - Holiday-Gift-Guide
  - Used-Book-Cellar
  - Giftsmith
bindings:
  - Hardcover
  - Paperback
  - Board Books

# Paypal
paypal_email: sfe@brooklinebooksmith.com
intervals:
  - Day
  - Week
  - Month
  - Year

subscription_recurring_times:
  - 3
  - 6
  - 9
  - 12
  - 24

_comments:
  link_to_buy_page: "Only necessary if the buy page is not the BBS shop site."
  featured_image_path: Upload images to the Uploads directory

box_classes: 'border rounded border-silver hover-bg-orange hover-white bg-transition'
## DO NOT EDIT BELOW THIS LINE
port: 4001
image_url: https://brooklinebbs.imgix.net
images_domain: //images.brooklinebooksmith.com
shop_domain: //www.brooklinebooksmith-shop.com

plugins_dir:  ./_app/_plugins
layouts_dir:  ./_app/_layouts
includes_dir: ./_app/_includes

incremental: true
# full_rebuild: false
gems:
  - jekyll-paginate
  - jekyll-seo-tag
env: development
sitename: brookline booksmith
timezone: Etc/Zulu
paginate: 40
paginate_path: "/blog/page-:num/"
exclude:
  - readme.md
  - todo.md
  - license.md
  - Gemfile
  - Gemfile.lock
  - bower.json
  - CNAME
  - node_modules
  - sass
  - gulpfile.js
  - package.json
  - javascript
  - vendor
include:
  - _pages
permalink: pretty
future: false
production: true
bust_css_cache: true
google_analytics_id: UA-xxxx
fancy_fonts:
  - ''
  - 'Fredericka+the+Great'
  - 'Cabin-sketch'
  - 'Lato'
  - 'Pacifico'
directory_assets_img: /static/images/


collections:
  events:
    output: true
    permalink: '/:collection/:path/'
    future: true
  books:
    output: false
  weekly_bestsellers:
    output: false
    hide_content: true
  staff:
    output: true
    permalink: '/:collection/:path/'
  landing_pages:
    output: true
    permalink: '/:path/'
  post_categories:
    output: true
    permalink: '/:path/'
  campaigns:
    output: false
  # first-edition-books:
  #   output: false
  #   commerce: 'subscription'
  programs:
    output: false
    permalink: '/:collection/:path/'

defaults:
  - scope:
      path: ''
      type: 'post_categories'
    values:
      layout: 'listing-category-posts'
      exclude_from_search: true
  - scope:
      path: ''
      type: pages
    values:
      layout: page-single
  - scope:
      path: ''
      type: posts
    values:
      layout: page-single
      _comments:
        featured: Stick to the top of the home page? Remember to uncheck when done.
  - scope:
      path: ''
      type: events
    values:
      layout: page-single
  - scope:
      path: ''
      type: landing_pages
    values:
      layout: page-single
  - scope:
      path: ''
      type: programs
    values:
      layout: page-single
  - scope:
      path: ''
      type: staff
    values:
      layout: page-single
  - scope:
      path: '_landing_pages/home.md'
    values:
      layout: home
      permalink: '/'
      fancy_font:
      title: 'brookline booksmith'
      page_heading:
      description: 'Brookline Booksmith is an stablished independent bookshop offering new & used titles, plus gifts, over 2 floors.'
      regenerate: true
  - scope:
      path: ''
      type: books
    values:
      _comments:
        image_path: "Click the link icon to add an image directly from the BBS shop page, when possible."


compress_html:
  ignore:
    envs: [development]
  profile: false
