#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build --incremental
# bundle exec htmlproof ./_site
bundle exec htmlproof ./_site --disable-external --check-html --alt-ignore '/.*/'
